"""Initial production database baseline.

Revision ID: 20260626_0001
Revises:
Create Date: 2026-06-26
"""

from typing import Sequence, Union

from alembic import op


revision: str = "20260626_0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _identity_primary_key() -> str:
    dialect = op.get_bind().dialect.name
    if dialect == "sqlite":
        return "INTEGER PRIMARY KEY AUTOINCREMENT"
    return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"


def _now_default() -> str:
    dialect = op.get_bind().dialect.name
    if dialect == "sqlite":
        return "datetime('now', 'localtime')"
    return "CURRENT_TIMESTAMP"


def _execute_all(statements: list[str]) -> None:
    for statement in statements:
        op.execute(statement)


def upgrade() -> None:
    pk = _identity_primary_key()
    now = _now_default()

    _execute_all([
        f"""
        CREATE TABLE IF NOT EXISTS travel_products (
            id {pk},
            title TEXT NOT NULL,
            destination TEXT NOT NULL,
            days INTEGER NOT NULL,
            price INTEGER NOT NULL,
            category TEXT NOT NULL,
            description TEXT,
            status TEXT NOT NULL DEFAULT 'active'
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS inquiries (
            id {pk},
            customer_name TEXT NOT NULL,
            phone TEXT,
            destination TEXT,
            people_count INTEGER,
            budget INTEGER,
            departure_date TEXT,
            message TEXT NOT NULL,
            follow_status TEXT NOT NULL DEFAULT 'new',
            source TEXT NOT NULL DEFAULT '未知',
            assigned_sales TEXT NOT NULL DEFAULT '未分配',
            priority TEXT NOT NULL DEFAULT 'medium',
            last_contact_at TEXT,
            next_follow_up_at TEXT,
            created_at TEXT NOT NULL DEFAULT ({now})
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS follow_up_tasks (
            id {pk},
            inquiry_id INTEGER NOT NULL,
            assigned_sales TEXT NOT NULL DEFAULT '未分配',
            task_title TEXT NOT NULL,
            task_status TEXT NOT NULL DEFAULT 'pending'
                CHECK (task_status IN ('pending', 'done', 'cancelled')),
            priority TEXT NOT NULL DEFAULT 'medium'
                CHECK (priority IN ('high', 'medium', 'low')),
            due_at TEXT,
            completed_at TEXT,
            created_at TEXT NOT NULL DEFAULT ({now}),
            FOREIGN KEY (inquiry_id) REFERENCES inquiries(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS travel_transport_resources (
            id {pk},
            destination TEXT NOT NULL,
            resource_name TEXT NOT NULL,
            supplier_name TEXT NOT NULL,
            transport_type TEXT NOT NULL,
            departure_city TEXT NOT NULL,
            arrival_city TEXT NOT NULL,
            cost_price REAL NOT NULL CHECK (cost_price >= 0),
            sale_price REAL NOT NULL CHECK (sale_price >= 0),
            stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
            sold_quantity INTEGER NOT NULL DEFAULT 0 CHECK (sold_quantity >= 0),
            reserved_quantity INTEGER NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
            currency TEXT NOT NULL DEFAULT 'CNY',
            available_start_date TEXT,
            available_end_date TEXT,
            available_dates TEXT,
            status TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'inactive')),
            created_at TEXT NOT NULL DEFAULT ({now}),
            CHECK (sold_quantity + reserved_quantity <= stock_quantity),
            CHECK (
                available_start_date IS NULL
                OR available_end_date IS NULL
                OR available_start_date <= available_end_date
            )
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS hotel_room_resources (
            id {pk},
            destination TEXT NOT NULL,
            resource_name TEXT NOT NULL,
            supplier_name TEXT NOT NULL,
            hotel_name TEXT NOT NULL,
            room_type TEXT NOT NULL,
            breakfast_included INTEGER NOT NULL DEFAULT 0
                CHECK (breakfast_included IN (0, 1)),
            max_occupancy INTEGER NOT NULL CHECK (max_occupancy > 0),
            cost_price REAL NOT NULL CHECK (cost_price >= 0),
            sale_price REAL NOT NULL CHECK (sale_price >= 0),
            stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
            sold_quantity INTEGER NOT NULL DEFAULT 0 CHECK (sold_quantity >= 0),
            reserved_quantity INTEGER NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
            currency TEXT NOT NULL DEFAULT 'CNY',
            available_start_date TEXT,
            available_end_date TEXT,
            available_dates TEXT,
            status TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'inactive')),
            created_at TEXT NOT NULL DEFAULT ({now}),
            CHECK (sold_quantity + reserved_quantity <= stock_quantity),
            CHECK (
                available_start_date IS NULL
                OR available_end_date IS NULL
                OR available_start_date <= available_end_date
            )
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS attraction_ticket_resources (
            id {pk},
            destination TEXT NOT NULL,
            resource_name TEXT NOT NULL,
            supplier_name TEXT NOT NULL,
            cost_price REAL NOT NULL CHECK (cost_price >= 0),
            sale_price REAL NOT NULL CHECK (sale_price >= 0),
            stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
            sold_quantity INTEGER NOT NULL DEFAULT 0 CHECK (sold_quantity >= 0),
            reserved_quantity INTEGER NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
            currency TEXT NOT NULL DEFAULT 'CNY',
            available_start_date TEXT,
            available_end_date TEXT,
            available_dates TEXT,
            status TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'inactive')),
            created_at TEXT NOT NULL DEFAULT ({now}),
            CHECK (sold_quantity + reserved_quantity <= stock_quantity),
            CHECK (
                available_start_date IS NULL
                OR available_end_date IS NULL
                OR available_start_date <= available_end_date
            )
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS restaurant_meal_resources (
            id {pk},
            destination TEXT NOT NULL,
            resource_name TEXT NOT NULL,
            supplier_name TEXT NOT NULL,
            meal_type TEXT NOT NULL,
            price_per_person REAL NOT NULL CHECK (price_per_person >= 0),
            cost_price REAL NOT NULL CHECK (cost_price >= 0),
            sale_price REAL NOT NULL CHECK (sale_price >= 0),
            stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
            sold_quantity INTEGER NOT NULL DEFAULT 0 CHECK (sold_quantity >= 0),
            reserved_quantity INTEGER NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
            currency TEXT NOT NULL DEFAULT 'CNY',
            available_start_date TEXT,
            available_end_date TEXT,
            available_dates TEXT,
            status TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'inactive')),
            created_at TEXT NOT NULL DEFAULT ({now}),
            CHECK (sold_quantity + reserved_quantity <= stock_quantity),
            CHECK (
                available_start_date IS NULL
                OR available_end_date IS NULL
                OR available_start_date <= available_end_date
            )
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS activity_resources (
            id {pk},
            destination TEXT NOT NULL,
            resource_name TEXT NOT NULL,
            supplier_name TEXT NOT NULL,
            activity_type TEXT NOT NULL,
            duration TEXT NOT NULL,
            suitable_people TEXT NOT NULL,
            cost_price REAL NOT NULL CHECK (cost_price >= 0),
            sale_price REAL NOT NULL CHECK (sale_price >= 0),
            stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
            sold_quantity INTEGER NOT NULL DEFAULT 0 CHECK (sold_quantity >= 0),
            reserved_quantity INTEGER NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
            currency TEXT NOT NULL DEFAULT 'CNY',
            available_start_date TEXT,
            available_end_date TEXT,
            available_dates TEXT,
            status TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'inactive')),
            created_at TEXT NOT NULL DEFAULT ({now}),
            CHECK (sold_quantity + reserved_quantity <= stock_quantity),
            CHECK (
                available_start_date IS NULL
                OR available_end_date IS NULL
                OR available_start_date <= available_end_date
            )
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS orders (
            id {pk},
            order_no TEXT NOT NULL UNIQUE,
            inquiry_id INTEGER,
            customer_name TEXT NOT NULL,
            phone TEXT,
            destination TEXT NOT NULL,
            people_count INTEGER NOT NULL DEFAULT 1 CHECK (people_count > 0),
            total_amount REAL NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
            paid_amount REAL NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
            order_status TEXT NOT NULL DEFAULT 'draft'
                CHECK (
                    order_status IN (
                        'draft', 'pending_payment', 'paid', 'fulfilling',
                        'completed', 'cancelled'
                    )
                ),
            payment_status TEXT NOT NULL DEFAULT 'unpaid'
                CHECK (payment_status IN ('unpaid', 'mock_paid', 'refunded')),
            fulfillment_status TEXT NOT NULL DEFAULT 'pending'
                CHECK (
                    fulfillment_status IN (
                        'pending', 'documents_pending', 'contract_pending',
                        'ready_to_travel', 'in_progress', 'completed'
                    )
                ),
            created_at TEXT NOT NULL DEFAULT ({now}),
            updated_at TEXT NOT NULL DEFAULT ({now}),
            FOREIGN KEY (inquiry_id) REFERENCES inquiries(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS order_items (
            id {pk},
            order_id INTEGER NOT NULL,
            resource_type TEXT NOT NULL
                CHECK (
                    resource_type IN (
                        'transport', 'hotel_room', 'attraction_ticket',
                        'restaurant_meal', 'activity'
                    )
                ),
            resource_id INTEGER NOT NULL,
            quantity INTEGER NOT NULL CHECK (quantity > 0),
            unit_price REAL NOT NULL CHECK (unit_price >= 0),
            total_price REAL NOT NULL CHECK (total_price >= 0),
            FOREIGN KEY (order_id) REFERENCES orders(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS order_documents (
            id {pk},
            order_id INTEGER NOT NULL,
            customer_name TEXT NOT NULL,
            document_type TEXT NOT NULL,
            document_number TEXT NOT NULL,
            file_name TEXT,
            file_url TEXT,
            ocr_status TEXT NOT NULL DEFAULT 'pending'
                CHECK (ocr_status = 'pending'),
            ocr_raw_text TEXT,
            verified_status TEXT NOT NULL DEFAULT 'pending'
                CHECK (verified_status IN ('pending', 'verified', 'rejected')),
            created_at TEXT NOT NULL DEFAULT ({now}),
            FOREIGN KEY (order_id) REFERENCES orders(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS insurance_products (
            id {pk},
            name TEXT NOT NULL,
            provider TEXT NOT NULL,
            coverage_summary TEXT,
            price REAL NOT NULL CHECK (price >= 0),
            status TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'inactive'))
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS order_insurances (
            id {pk},
            order_id INTEGER NOT NULL,
            insurance_product_id INTEGER NOT NULL,
            insured_customer_name TEXT NOT NULL,
            price REAL NOT NULL CHECK (price >= 0),
            FOREIGN KEY (order_id) REFERENCES orders(id),
            FOREIGN KEY (insurance_product_id) REFERENCES insurance_products(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS order_contracts (
            id {pk},
            order_id INTEGER NOT NULL,
            contract_no TEXT NOT NULL UNIQUE,
            contract_status TEXT NOT NULL DEFAULT 'generated'
                CHECK (contract_status IN ('generated', 'signed')),
            contract_content TEXT NOT NULL,
            signed_at TEXT,
            FOREIGN KEY (order_id) REFERENCES orders(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS order_reminders (
            id {pk},
            order_id INTEGER NOT NULL,
            reminder_type TEXT NOT NULL,
            title TEXT NOT NULL,
            message TEXT NOT NULL,
            remind_at TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'completed', 'cancelled')),
            FOREIGN KEY (order_id) REFERENCES orders(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS payment_events (
            id {pk},
            payment_event_id TEXT NOT NULL UNIQUE,
            order_id INTEGER NOT NULL,
            event_status TEXT NOT NULL DEFAULT 'processing'
                CHECK (event_status IN ('processing', 'processed')),
            response_json TEXT,
            created_at TEXT NOT NULL DEFAULT ({now}),
            processed_at TEXT,
            FOREIGN KEY (order_id) REFERENCES orders(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS quotes (
            id {pk},
            quote_no TEXT NOT NULL UNIQUE,
            inquiry_id INTEGER,
            customer_name TEXT NOT NULL,
            phone TEXT,
            destination TEXT NOT NULL,
            people_count INTEGER NOT NULL DEFAULT 1 CHECK (people_count > 0),
            customer_budget REAL CHECK (customer_budget IS NULL OR customer_budget >= 0),
            target_margin REAL NOT NULL CHECK (target_margin >= 0 AND target_margin < 1),
            base_cost REAL NOT NULL DEFAULT 0 CHECK (base_cost >= 0),
            base_price REAL NOT NULL DEFAULT 0 CHECK (base_price >= 0),
            dynamic_adjustment REAL NOT NULL DEFAULT 0,
            final_price REAL NOT NULL DEFAULT 0 CHECK (final_price >= 0),
            estimated_profit REAL NOT NULL DEFAULT 0,
            estimated_margin REAL NOT NULL DEFAULT 0,
            quote_status TEXT NOT NULL DEFAULT 'draft'
                CHECK (
                    quote_status IN (
                        'draft', 'proposed', 'accepted', 'rejected',
                        'expired', 'converted_to_order'
                    )
                ),
            pricing_strategy TEXT NOT NULL DEFAULT 'mixed'
                CHECK (
                    pricing_strategy IN (
                        'cost_plus', 'budget_based', 'inventory_based',
                        'margin_protection', 'mixed'
                    )
                ),
            risk_flags TEXT NOT NULL DEFAULT '[]',
            recommendation TEXT,
            departure_date TEXT,
            converted_order_id INTEGER UNIQUE,
            created_at TEXT NOT NULL DEFAULT ({now}),
            updated_at TEXT NOT NULL DEFAULT ({now}),
            FOREIGN KEY (inquiry_id) REFERENCES inquiries(id),
            FOREIGN KEY (converted_order_id) REFERENCES orders(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS quote_items (
            id {pk},
            quote_id INTEGER NOT NULL,
            resource_type TEXT NOT NULL
                CHECK (
                    resource_type IN (
                        'transport', 'hotel_room', 'attraction_ticket',
                        'restaurant_meal', 'activity'
                    )
                ),
            resource_id INTEGER NOT NULL,
            resource_name TEXT NOT NULL,
            quantity INTEGER NOT NULL CHECK (quantity > 0),
            unit_cost REAL NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
            unit_price REAL NOT NULL DEFAULT 0 CHECK (unit_price >= 0),
            total_cost REAL NOT NULL DEFAULT 0 CHECK (total_cost >= 0),
            total_price REAL NOT NULL DEFAULT 0 CHECK (total_price >= 0),
            margin REAL NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT ({now}),
            FOREIGN KEY (quote_id) REFERENCES quotes(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS sales_conversion_records (
            id {pk},
            inquiry_id INTEGER,
            quote_id INTEGER NOT NULL,
            customer_name TEXT NOT NULL,
            phone TEXT,
            destination TEXT NOT NULL,
            budget REAL CHECK (budget IS NULL OR budget >= 0),
            final_price REAL NOT NULL CHECK (final_price >= 0),
            conversion_probability REAL NOT NULL
                CHECK (conversion_probability >= 0 AND conversion_probability <= 1),
            conversion_stage TEXT NOT NULL DEFAULT 'new'
                CHECK (
                    conversion_stage IN (
                        'new', 'quoted', 'negotiating', 'high_intent',
                        'low_intent', 'accepted', 'lost', 'converted'
                    )
                ),
            customer_objections_json TEXT NOT NULL DEFAULT '[]',
            recommended_actions_json TEXT NOT NULL DEFAULT '[]',
            follow_up_script TEXT NOT NULL,
            risk_flags_json TEXT NOT NULL DEFAULT '[]',
            next_best_action TEXT NOT NULL,
            assigned_sales TEXT NOT NULL DEFAULT '未分配',
            created_at TEXT NOT NULL DEFAULT ({now}),
            updated_at TEXT NOT NULL DEFAULT ({now}),
            FOREIGN KEY (inquiry_id) REFERENCES inquiries(id),
            FOREIGN KEY (quote_id) REFERENCES quotes(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS content_campaigns (
            id {pk},
            campaign_name TEXT NOT NULL,
            destination TEXT NOT NULL,
            product_theme TEXT NOT NULL,
            target_audience TEXT NOT NULL,
            platform TEXT NOT NULL
                CHECK (platform IN ('xiaohongshu', 'douyin', 'video_account', 'wechat', 'website')),
            content_type TEXT NOT NULL
                CHECK (content_type IN ('note', 'short_video_script', 'poster_copy', 'itinerary_post', 'promotion_post')),
            title TEXT NOT NULL,
            body TEXT NOT NULL,
            hashtags_json TEXT NOT NULL DEFAULT '[]',
            call_to_action TEXT NOT NULL,
            related_product_id INTEGER,
            related_resource_ids_json TEXT NOT NULL DEFAULT '[]',
            estimated_margin REAL NOT NULL DEFAULT 0,
            priority_score REAL NOT NULL DEFAULT 0 CHECK (priority_score >= 0 AND priority_score <= 100),
            status TEXT NOT NULL DEFAULT 'draft'
                CHECK (status IN ('draft', 'ready', 'published', 'archived')),
            published_at TEXT,
            created_at TEXT NOT NULL DEFAULT ({now}),
            updated_at TEXT NOT NULL DEFAULT ({now}),
            FOREIGN KEY (related_product_id) REFERENCES travel_products(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS customer_profiles (
            id {pk},
            customer_name TEXT NOT NULL,
            phone TEXT,
            customer_level TEXT NOT NULL DEFAULT 'regular'
                CHECK (customer_level IN ('regular', 'high_value')),
            total_orders INTEGER NOT NULL DEFAULT 0 CHECK (total_orders >= 0),
            total_spent REAL NOT NULL DEFAULT 0 CHECK (total_spent >= 0),
            total_profit REAL NOT NULL DEFAULT 0,
            preferred_destinations_json TEXT NOT NULL DEFAULT '[]',
            preferred_budget_range TEXT,
            last_order_at TEXT,
            next_repurchase_date TEXT,
            repurchase_probability REAL NOT NULL DEFAULT 0
                CHECK (repurchase_probability >= 0 AND repurchase_probability <= 1),
            lifecycle_stage TEXT NOT NULL DEFAULT 'new'
                CHECK (lifecycle_stage IN ('new', 'active', 'high_value', 'dormant', 'lost')),
            risk_flags_json TEXT NOT NULL DEFAULT '[]',
            recommendation_text TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT ({now}),
            updated_at TEXT NOT NULL DEFAULT ({now})
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS repurchase_tasks (
            id {pk},
            customer_profile_id INTEGER NOT NULL,
            customer_name TEXT NOT NULL,
            phone TEXT,
            recommended_destination TEXT,
            recommended_product_id INTEGER,
            reason TEXT NOT NULL,
            priority TEXT NOT NULL DEFAULT 'medium'
                CHECK (priority IN ('high', 'medium', 'low')),
            due_date TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'completed', 'cancelled')),
            assigned_sales TEXT NOT NULL DEFAULT '未分配',
            created_at TEXT NOT NULL DEFAULT ({now}),
            completed_at TEXT,
            FOREIGN KEY (customer_profile_id) REFERENCES customer_profiles(id),
            FOREIGN KEY (recommended_product_id) REFERENCES travel_products(id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS supplier_performance (
            id {pk},
            supplier_name TEXT NOT NULL,
            resource_type TEXT NOT NULL,
            destination TEXT NOT NULL,
            total_resources INTEGER NOT NULL DEFAULT 0 CHECK (total_resources >= 0),
            total_orders INTEGER NOT NULL DEFAULT 0 CHECK (total_orders >= 0),
            total_revenue REAL NOT NULL DEFAULT 0,
            total_cost REAL NOT NULL DEFAULT 0,
            total_profit REAL NOT NULL DEFAULT 0,
            average_margin REAL NOT NULL DEFAULT 0,
            stockout_count INTEGER NOT NULL DEFAULT 0 CHECK (stockout_count >= 0),
            cancellation_count INTEGER NOT NULL DEFAULT 0 CHECK (cancellation_count >= 0),
            performance_score REAL NOT NULL DEFAULT 0
                CHECK (performance_score >= 0 AND performance_score <= 100),
            risk_flags_json TEXT NOT NULL DEFAULT '[]',
            recommendation_text TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT ({now}),
            updated_at TEXT NOT NULL DEFAULT ({now}),
            UNIQUE (supplier_name, resource_type, destination)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS procurement_suggestions (
            id {pk},
            supplier_name TEXT NOT NULL,
            resource_type TEXT NOT NULL,
            destination TEXT NOT NULL,
            suggested_action TEXT NOT NULL
                CHECK (suggested_action IN ('increase_stock', 'reduce_stock', 'renegotiate_price', 'replace_supplier', 'keep_monitoring')),
            suggested_quantity INTEGER NOT NULL DEFAULT 0 CHECK (suggested_quantity >= 0),
            reason TEXT NOT NULL,
            priority TEXT NOT NULL DEFAULT 'medium'
                CHECK (priority IN ('high', 'medium', 'low')),
            status TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'accepted', 'completed', 'dismissed')),
            created_at TEXT NOT NULL DEFAULT ({now}),
            updated_at TEXT NOT NULL DEFAULT ({now})
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS finance_records (
            id {pk},
            order_id INTEGER NOT NULL,
            record_type TEXT NOT NULL
                CHECK (record_type IN ('receivable', 'payable', 'refund', 'supplier_cost', 'insurance_income', 'adjustment')),
            amount REAL NOT NULL CHECK (amount >= 0),
            direction TEXT NOT NULL CHECK (direction IN ('income', 'expense')),
            counterparty TEXT NOT NULL,
            due_date TEXT,
            paid_at TEXT,
            status TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'paid', 'overdue', 'cancelled', 'disputed')),
            risk_flags_json TEXT NOT NULL DEFAULT '[]',
            note TEXT,
            created_at TEXT NOT NULL DEFAULT ({now}),
            updated_at TEXT NOT NULL DEFAULT ({now}),
            FOREIGN KEY (order_id) REFERENCES orders(id),
            UNIQUE (order_id, record_type, counterparty)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS reconciliation_reports (
            id {pk},
            report_date TEXT NOT NULL UNIQUE,
            total_receivable REAL NOT NULL DEFAULT 0,
            total_received REAL NOT NULL DEFAULT 0,
            total_payable REAL NOT NULL DEFAULT 0,
            total_paid REAL NOT NULL DEFAULT 0,
            gross_profit REAL NOT NULL DEFAULT 0,
            risk_amount REAL NOT NULL DEFAULT 0,
            risk_flags_json TEXT NOT NULL DEFAULT '[]',
            recommendation_text TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT ({now})
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS operation_audit_logs (
            id {pk},
            operation_type TEXT NOT NULL,
            module_name TEXT NOT NULL,
            resource_type TEXT,
            resource_id TEXT,
            actor TEXT NOT NULL DEFAULT 'internal-beta',
            request_id TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'success'
                CHECK (status IN ('success', 'failed', 'skipped')),
            detail_json TEXT NOT NULL DEFAULT '{{}}',
            created_at TEXT NOT NULL DEFAULT ({now})
        )
        """,
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_follow_up_tasks_active_inquiry
        ON follow_up_tasks (inquiry_id)
        WHERE task_status IN ('pending', 'done')
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_follow_up_tasks_sales_status_due
        ON follow_up_tasks (assigned_sales, task_status, due_at)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_travel_transport_resources_filters
        ON travel_transport_resources (destination, status, supplier_name, cost_price)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_hotel_room_resources_filters
        ON hotel_room_resources (destination, status, supplier_name, cost_price)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_attraction_ticket_resources_filters
        ON attraction_ticket_resources (destination, status, supplier_name, cost_price)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_restaurant_meal_resources_filters
        ON restaurant_meal_resources (destination, status, supplier_name, cost_price)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_activity_resources_filters
        ON activity_resources (destination, status, supplier_name, cost_price)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_orders_status
        ON orders (order_status, payment_status, fulfillment_status, created_at)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_order_items_order
        ON order_items (order_id)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_order_documents_order
        ON order_documents (order_id)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_order_insurances_order
        ON order_insurances (order_id)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_order_contracts_order
        ON order_contracts (order_id)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_order_reminders_order_status
        ON order_reminders (order_id, status, remind_at)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_payment_events_order
        ON payment_events (order_id, event_status)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_quotes_filters
        ON quotes (destination, quote_status, inquiry_id, created_at)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_quotes_margin_price
        ON quotes (estimated_margin, final_price)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_quote_items_quote
        ON quote_items (quote_id, id)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_sales_conversion_priority
        ON sales_conversion_records (
            conversion_stage, conversion_probability, updated_at
        )
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_sales_conversion_quote
        ON sales_conversion_records (quote_id, inquiry_id)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_content_campaigns_calendar
        ON content_campaigns (status, created_at, platform, destination)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_content_campaigns_priority
        ON content_campaigns (priority_score, estimated_margin)
        """,
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_customer_profiles_identity
        ON customer_profiles (customer_name, COALESCE(phone, ''))
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_customer_profiles_value
        ON customer_profiles (customer_level, lifecycle_stage, repurchase_probability)
        """,
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_repurchase_tasks_active_profile
        ON repurchase_tasks (customer_profile_id)
        WHERE status = 'pending'
        """,
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_procurement_suggestions_active
        ON procurement_suggestions (supplier_name, resource_type, destination, suggested_action)
        WHERE status IN ('pending', 'accepted')
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_supplier_performance_risk
        ON supplier_performance (performance_score, stockout_count, cancellation_count)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_finance_records_reconciliation
        ON finance_records (status, direction, record_type, due_date, order_id)
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_operation_audit_logs_filters
        ON operation_audit_logs (
            module_name, operation_type, resource_type, actor, created_at
        )
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_operation_audit_logs_request
        ON operation_audit_logs (request_id)
        """,
    ])


def downgrade() -> None:
    raise RuntimeError(
        "Reverse baseline migration is disabled. Restore a verified backup "
        "and use a forward migration after manual approval."
    )
